### PR TITLE
fix(prodsample): configureRequestLog had faulty example code

### PR DESCRIPTION
**Pull request by Matthew-Mallimo**
FIxing #445 
## Description

example code had dangerous object references
## Motivation and Context

Provide better examples
## How Has This Been Tested?

N/A
## Types of Changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

### CODE REVIEW

**Review by JAdshead — DISMISSED** [review]

**Review by 10xLaCroixDrinker — APPROVED** [review]

**Review by 10xLaCroixDrinker — CHANGES_REQUESTED** [review]
The commit type needs to be `test` or maybe `docs` as this is not fixing the app itself

**Comment by Matthew-Mallimo** [comment]
> The commit type needs to be `test` or maybe `docs` as this is not fixing the app itself

Fixed, used `docs`

**Review by 10xLaCroixDrinker — APPROVED** [review]

**Review by JAdshead — APPROVED** [review]

**Comment by 10xLaCroixDrinker** [comment]
The commit in the merge had the type "fix"

**Comment by Matthew-Mallimo** [comment]
> The commit in the merge had the type "fix"

Gah, it took from the PR description. My bad

**Pull request merged**
