### PR TITLE
fix(devCdn): only cache 200's

### PR DESCRIPTION
**Pull request by code-forger**
## Description
Prevent the caching and re-playing of non 200 reponses.

## Motivation and Context
if there is a non-200 reponse, the cache will re-play the text content as a '200'. This means errors are stored in the cache and re-played incorrectly. 

Simply do not cache the non 200

## How Has This Been Tested?
TBT

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

### CODE REVIEW

**Comment by code-forger** [comment]
> Ideally we would cache anything that is `ok == true` but then you would have to cache the status too.

Thats a better approach, will use that

**Comment by smackfu** [comment]
Something to consider is that there is a single cache across the whole system, so any changes to the cache file have to be backwards compatible.  Which may make it impossible to cache status.

**Review by smackfu — APPROVED** [review]

**Review by bishnubista — APPROVED** [review]

**Comment by 10xLaCroixDrinker** [comment]
> > Ideally we would cache anything that is `ok == true` but then you would have to cache the status too.
> 
> Thats a better approach, will use that

@code-forger are you making this change?

**Comment by code-forger** [comment]
@smackfu @10xLaCroixDrinker 

On second look, I think caching the status code is to much for this simple cache.

This is a CDN cache, the CDN should always be responding with 200's, I don't see any other 2XX code it would be useful to cache.

**Review by 10xLaCroixDrinker — APPROVED** [review]

**Pull request merged**
