### PR TITLE
chore(deps): remove acorn

### PR DESCRIPTION
**Pull request by JAdshead**
## Description

Removing unused dev dep

## Motivation and Context

Acorn appears to not be used. I have tracked its addition back to when it was introduced in one app v4 and cannot find a reason for it. 

## How Has This Been Tested?

I am relying on the integration tests to catch if this is really necessary. I did not see any peer dep warnings after uninstalling and running `npm i`

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update
- [ ] Security update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

### CODE REVIEW

**Comment by 10xLaCroixDrinker** [comment]
acorn was added to resolve a webpack issue

**Comment by 10xLaCroixDrinker** [comment]
If you `npm ls acorn`, does it still show up in dependencies at all?

**Comment by JAdshead** [comment]
> If you `npm ls acorn`, does it still show up in dependencies at all? I'd suspect so seeing so few changes in the lockfile.

yes it does, the version used by webpack is 6.4.2 so not sure how including another version altogether (`7.3.1`) would help 

```
@americanexpress/one-app@5.15.1 /Users/jadshead/AMEX/one-app
├─┬ @americanexpress/one-app-bundler@6.15.0
│ └─┬ webpack@4.46.0
│   └── acorn@6.4.2
├─┬ @americanexpress/one-app-dev-cdn@3.3.2
│ └─┬ proxy-agent@5.0.0
│   └─┬ pac-proxy-agent@5.0.0
│     └─┬ pac-resolver@5.0.0
│       └─┬ degenerator@3.0.2
│         └─┬ vm2@3.9.9
│           └── acorn@8.7.0
├─┬ @commitlint/cli@16.2.3
│ └─┬ @commitlint/load@16.2.3
│   └─┬ cosmiconfig-typescript-loader@1.0.9
│     └─┬ ts-node@10.7.0
│       └── acorn@8.7.0
├─┬ eslint@7.32.0
│ └─┬ espree@7.3.1
│   ├─┬ acorn-jsx@5.3.2
│   │ └── acorn@7.4.1 deduped
│   └── acorn@7.4.1
├─┬ jest@27.5.1
│ └─┬ @jest/core@27.5.1
│   └─┬ jest-config@27.5.1
│     └─┬ jest-environment-jsdom@27.5.1
│       └─┬ jsdom@16.7.0
│         ├─┬ acorn-globals@6.0.0
│         │ └── acorn@7.4.1 deduped
│         └── acorn@8.7.0
└─┬ rollup-plugin-terser@7.0.2
  └─┬ terser@5.12.1
    └── acorn@8.7.0
```

**Review by dogpatch626 — COMMENTED** [review]
Is this mainly for removing bundle size or just for the sake of removing unnecessary packages

**Comment by JAdshead** [comment]
> Is this mainly for removing bundle size or just for the sake of removing unnecessary packages

As this is a dev dep it won't affect the final bundle size so this is just for removing unnecessary packages as it creates a maintenance overhead.

**Review by dogpatch626 — APPROVED** [review]

**Pull request merged**
