### PR TITLE
chores : fix typos in docs

### PR DESCRIPTION
**Pull request by shivaylamba**
## Description
Fix grammatical errors across project. Fixes Issue #117 

## Motivation and Context
Helps improve the documentation and readability. 

## How Has This Been Tested?
Ran locally after making the changes. 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation (adding or updating documentation)

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] These changes should be applied to a maintenance branch.
- [ ] This change requires cross browser checks.
- [ ] Performance tests should be ran against the server prior to merging.
- [ ] This change impacts caching for client browsers.
- [ ] This change impacts HTTP headers.
- [ ] This change adds additional environment variable requirements for One App users.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using One App?

It just helps improve code readability and quality.

### CODE REVIEW

**Comment by mtomcal** [comment]
Thanks @shivaylamba for your contribution. We appreciate the help. This looks great. If you could reword the commit message to follow our commit message format (more info and link here: https://travis-ci.org/github/americanexpress/one-app/jobs/679149712#L667-L672) that would be great!

**Comment by shivaylamba** [comment]
@mtomcal  I have also fixed Issue #118  in this PR

**Comment by shivaylamba** [comment]
Okay I will follow the commit message format according to the one mentioned in the travis ci

**Comment by shivaylamba** [comment]
@mtomcal I have changed the commit message

**Comment by mtomcal** [comment]
Looks like `chore(typos fix): fix typos in docs` would perhaps be better as `chore(typos): fix typos in docs` per https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-scope. We have git precommit hook that should run `npm run test:git-history`. Does that work on your end?

**Comment by mtomcal** [comment]
You may need to `git rebase -i master` and add `rw` to `chore(typos fix): fix typos in docs` you can change to `chore(typos): fix typos in docs`.

**Comment by shivaylamba** [comment]
@mtomcal could you review it now?

**Comment by shivaylamba** [comment]
I used git rebase only

**Comment by mtomcal** [comment]
Hooray Unit Tests and Git Commit tests passed! Approved. Just need Integration Test to finish and we'll be set.

**Comment by shivaylamba** [comment]
Great!

**Pull request merged**
